### ISSUE TITLE
oh cool

### ISSUE THREAD

**Issue by sethvincent** [loganfranken/scour-github#1]
it would be neat to be able to do something like:

```
github-search seattle | output.txt
```

:ghost: :dash:

**Comment by loganfranken** [comment]
:+1: Will do!

**Comment by loganfranken** [comment]
I want to keep playing around w/ the implementation before I push it to `npm` and all, but I think this roughly does what you wanted:

```
node scour-github.js ucsb > results.txt
```

I wanted a way to output this to a nice list of links I could quickly click through, so I would personally recommend using the `--html` flag:

```
node scour-github.js seattle --html > results.html
```

**Comment by loganfranken** [comment]
Let me know if I missed the mark or if there's anything else I could add to make it more useful for you!

**Comment by sethvincent** [comment]
Awesome! That's a good rename, too.
